const routes = {
    home: "/home",
    login: "/login",
    register: "/register",
    productDetail:"/product-detail/:id/product",
    product: "/product-category/:id",
    // checkout: "/checkout",
    // sellerManager: "/seller",
    // productDetail: "/product-detail/:id/product",
    // product: "/product-industrial/:id/:name",
    // productList: "/product-list",
    // productListAll: "/product/list/all-seller/:id/shop",
    // addProduct: "/product/new",
    // editProduct: "/product/edit/:shopId/product",
    // shopProfile: "/shop/profile/:shopId",
    // verifyCodeRegister: "/vertify-code",
    // createPassword: "/create-password",
    // informationUser: "/info-user",
};
export default routes;